name: CI
on:
  push:
    branches: [ build ]
  schedule:
    - cron:  0 8 * * *
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
    - uses: actions/checkout@v2
      with:
        ref: build
    - uses: bahmutov/npm-install@v1
    - name: Build
      run: yarn run build
      env:
        WAKATIME_KEY: ${{ secrets.WAKATIME_KEY }}
    - name: Commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Update" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
