name: CI
on:
  push:
    branches: [ build ]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
    - uses: actions/checkout@v2
      with:
        ref: build
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Run
      run: |
        yarn install
        yarn run build
    - name: Commit
      run: |
        cd dist
        git add .
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -m "init" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        forcce: true
        branch: master
